Repository qaml-bootcamp-java-selenium-jul2022/QAML_PrimerSelenium, pull requests merged in 2022-09, with the labels that each got.

#2 Subiendo tarea1
  .idea/compiler.xml
  pom.xml
  src/main/java/Steps/BaseSteps.java
  src/main/java/Steps/PrimerSteps.java
  src/test/java/BaseTest.java
  src/test/java/PrimerTest.java
Labels: Gerry

#14 Ejercicios Páginas ToolsQA y PracticeTestAutomation
  src/main/java/Pages/PracticetestautomationPage.java
  src/main/java/Pages/ToolsQAPage.java
  src/main/java/Steps/PracticetestautomationSteps.java
  src/main/java/Steps/ToolsQASteps.java
  src/test/java/PracticetestautomationTests.java
  src/test/java/ToolQAtest.java
Labels: Monica, Tarea, EjercicioEnClase

#15 Ultimo commit con la tarea de ejercicios para AutomationPractice y DemoQA
  .gitignore
  src/main/java/Pages/AutomationPracticePage.java
  src/main/java/Pages/DemoQAPage.java
  src/main/java/Pages/MyFirstWebPage.java
  src/main/java/Pages/PracticeAutomationPage.java
  src/main/java/Pages/YouTubePage.java
  src/main/java/Steps/AutomationPracticeSteps.java
  src/main/java/Steps/BaseSteps.java
  src/main/java/Steps/DemoQASteps.java
  src/main/java/Steps/MyFirstWebPageSteps.java
  src/main/java/Steps/PracticeAutomationSteps.java
  src/main/java/Steps/PrimerSteps.java
  src/main/java/Steps/YouTubeSteps.java
  src/test/java/AutomationPracticeTests.java
  src/test/java/BaseTest.java
  src/test/java/DemoQATest.java
  src/test/java/EjerciciosEnClaseTest.java
  src/test/java/MyFirstWebPageTests.java
  src/test/java/PracticeAutomationTest.java
  src/test/java/PrimerTest.java
  src/test/java/YouTubeTest.java
Labels: Monica, Alvaro, Tarea, Susy
